#!/bin/bash

#SBATCH --job-name=convert-masks-to-rois
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:15:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system

# make output directory
mkdir -p rois

#copy content of masks folder to new roi folder
#find ./masks/ -maxdepth 1 -type f -print0 | xargs -0 mv -t ./rois

masks=`jq -r '.masks' config.json`
find $masks -maxdepth 1 -type f -print0 | xargs -0 mv -t ./rois

#for f in masks:
#  cp f in rois
