#!/bin/bash

#SBATCH --job-name=convert-masks-to-rois
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:15:00

set -e 
set -x

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system

# make output directory
mkdir -p output/rois

#copy content of masks folder to new rois folder
masks=`jq -r '.masks' config.json`
find $masks -maxdepth 1 -type f -print0 | xargs -0 mv -t ./rois

echo "all done"
